nav:
  - Participate.md
  - Getting Started:
    - Racer's Guide: Racer's Guide.md
    - Intro Categories
    - Women: Women.md
    - Starting a Team: Starting a Team.md
  - Racing Information:
    - Licenses.md
    - Categories.md
    - Upgrades.md
  - Club Officer Resources:
    - Club Resources/Club Resources.md