nav:
  - About.md
  - Conference Information:
    - Contact/
    - People:
      - People/Flyyn Leonard
      - People/Luke Knisley
      - People/Benjamin Kramer
  - Northeast Collegiate Cycling Corporation
  - NECCC Board